openapi: 3.0.2
info:
  title: VidDigest API
  version: 0.1.0
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
paths:
  /api/v1/gemini/chat:
    post:
      summary: Chat with Gemini
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
      responses:
        '200':
          description: OK
  /api/v1/plugins/list:
    get:
      summary: List plugins
      responses:
        '200':
          description: OK
