openapi: 3.0.2
info:
  title: VidDigest API
  version: 0.1.0
security:
  - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    VideoResult:
      type: object
      properties:
        transcript:
          type: string
        summary:
          type: string
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
paths:
  /api/v1/gemini/chat:
    post:
      summary: Chat with Gemini
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
      responses:
        '200':
          description: OK
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '500':
          description: Server error
      security:
        - ApiKeyAuth: []
  /api/v1/video/process:
    post:
      summary: Process uploaded video
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Aggregated result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoResult'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '500':
          description: Server error
      security:
        - ApiKeyAuth: []
  /api/v1/plugins/list:
    get:
      summary: List plugins
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
      security:
        - ApiKeyAuth: []
  /api/v1/plugins/load:
    post:
      summary: Load plugin jar
      parameters:
        - in: query
          name: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Loaded
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Invalid path
        '401':
          description: Unauthorized
      security:
        - ApiKeyAuth: []
  /api/v1/plugins/unload:
    post:
      summary: Unload plugin
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Unloaded
        '400':
          description: Invalid name
        '401':
          description: Unauthorized
      security:
        - ApiKeyAuth: []
